import Foundation
import Observation
import UIKit
import os

/// Checks GitHub's latest release against the running version and hands installs off to SideStore
/// (`sidestore://install?url=…`, handled by SideStore's URLHandler; it keeps app data like any update).
@MainActor @Observable
final class UpdateChecker {
    struct Release: Equatable {
        var version: String
        var ipaURL: URL
        var pageURL: URL
        var notes: String
    }

    enum Status: Equatable {
        case idle, checking, upToDate, failed(String)
    }

    static let repo = "KNIGHTABDO/linkup"
    /// Stable URL that always serves the newest release's SideStore source (generated by CI).
    static let sourceURL = URL(string: "https://github.com/\(repo)/releases/latest/download/apps.json")!

    private(set) var available: Release?
    private(set) var status: Status = .idle
    private var lastCheck: Date?

    private static let throttle: TimeInterval = 6 * 3600
    private static let dismissedKey = "dismissedUpdateVersion"
    private static let logger = Logger(subsystem: "com.knightabdo.linkup", category: "updates")

    var currentVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "0"
    }

    /// The banner stays hidden for a version the user dismissed; Settings still offers it.
    var showsBanner: Bool {
        guard let available else { return false }
        return UserDefaults.standard.string(forKey: Self.dismissedKey) != available.version
    }

    func dismissBanner() {
        guard let available else { return }
        UserDefaults.standard.set(available.version, forKey: Self.dismissedKey)
    }

    /// Launch / foreground check, at most every few hours. Network failures are only logged here.
    func checkIfDue() {
        guard DebugLaunch.screen == nil else { return }
        if let lastCheck, Date().timeIntervalSince(lastCheck) < Self.throttle { return }
        Task { await check() }
    }

    func check() async {
        guard status != .checking else { return }
        status = .checking
        lastCheck = Date()
        do {
            let release = try await fetchLatest()
            if Self.isVersion(release.version, newerThan: currentVersion) {
                available = release
                status = .idle
                Self.logger.info("update available: \(release.version, privacy: .public) (running \(self.currentVersion, privacy: .public))")
            } else {
                available = nil
                status = .upToDate
            }
        } catch {
            status = .failed(error.localizedDescription)
            Self.logger.warning("update check failed: \(error.localizedDescription, privacy: .public)")
        }
    }

    /// Opens SideStore's install flow; false when SideStore is not installed (caller falls back).
    func install(_ release: Release) async -> Bool {
        await open(Self.sideStoreURL(host: "install", url: release.ipaURL))
    }

    func addSourceToSideStore() async -> Bool {
        await open(Self.sideStoreURL(host: "source", url: Self.sourceURL))
    }

    private func open(_ url: URL?) async -> Bool {
        guard let url else { return false }
        let opened = await UIApplication.shared.open(url, options: [:])
        if !opened { Self.logger.warning("could not open \(url.scheme ?? "", privacy: .public)://\(url.host ?? "", privacy: .public) (SideStore missing?)") }
        return opened
    }

    private static func sideStoreURL(host: String, url: URL) -> URL? {
        var components = URLComponents()
        components.scheme = "sidestore"
        components.host = host
        components.queryItems = [URLQueryItem(name: "url", value: url.absoluteString)]
        return components.url
    }

    // MARK: GitHub

    private struct GitHubRelease: Decodable {
        struct Asset: Decodable {
            var name: String
            var browser_download_url: URL
        }
        var tag_name: String
        var html_url: URL
        var body: String?
        var draft: Bool?
        var prerelease: Bool?
        var assets: [Asset]
    }

    private enum UpdateError: LocalizedError {
        case badStatus(Int), noIPA
        var errorDescription: String? {
            switch self {
            case .badStatus(let code): return "GitHub returned HTTP \(code)"
            case .noIPA: return "The latest release has no IPA attached"
            }
        }
    }

    private func fetchLatest() async throws -> Release {
        var request = URLRequest(url: URL(string: "https://api.github.com/repos/\(Self.repo)/releases/latest")!,
                                 timeoutInterval: 20)
        request.setValue("application/vnd.github+json", forHTTPHeaderField: "Accept")
        request.setValue("Linkup/\(currentVersion)", forHTTPHeaderField: "User-Agent")
        let (data, response) = try await URLSession.shared.data(for: request)
        if let http = response as? HTTPURLResponse, http.statusCode != 200 { throw UpdateError.badStatus(http.statusCode) }
        let release = try JSONDecoder().decode(GitHubRelease.self, from: data)
        guard let ipa = release.assets.first(where: { $0.name == "Linkup.ipa" })
                ?? release.assets.first(where: { $0.name.lowercased().hasSuffix(".ipa") }) else { throw UpdateError.noIPA }
        let version = release.tag_name.hasPrefix("v") ? String(release.tag_name.dropFirst()) : release.tag_name
        return Release(version: version, ipaURL: ipa.browser_download_url, pageURL: release.html_url,
                       notes: release.body ?? "")
    }

    /// Numeric dotted comparison: "0.4.10" > "0.4.9".
    static func isVersion(_ candidate: String, newerThan current: String) -> Bool {
        let a = candidate.split(separator: ".").map { Int($0) ?? 0 }
        let b = current.split(separator: ".").map { Int($0) ?? 0 }
        for i in 0..<max(a.count, b.count) {
            let x = i < a.count ? a[i] : 0, y = i < b.count ? b[i] : 0
            if x != y { return x > y }
        }
        return false
    }
}
